notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk11
python: 3.7
os: linux
addons:
  apt:
    update: true
    packages:
      - curl
      - sudo
      - lsof
      - tree
      - python3-pip
install: true
before_install:
  - export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 3000 3001
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      name: test
      before_script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew browserSyncInstall
        - tree $TRAVIS_BUILD_DIR/build/gradle-browser-sync/node_modules/.bin
        - cd $TRAVIS_BUILD_DIR && ./gradlew browserSyncStart &
        - wait_for 3000 3001
      script:
        - http :3000
      after_script: cd $TRAVIS_BUILD_DIR && ./gradlew --stop
cache:
  pip: true
  packages: true
  directories:
    - ~/.local/daggerok
    - ~/.gradle
    - ~/.n*
